name: MyST GitHub Pages Deploy
on:
  push:
    branches:
      - main
  pull_request:

env:
  BASE_URL: /${{ github.event.repository.name }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm install -g mystmd
      - run: myst build --html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_build/html
      - uses: actions/deploy-pages@v4
        id: deployment

permissions:
  contents: read
  id-token: write
  pages: write
